services:
  mysql:
    image: mysql:latest
    container_name: hotel-inventory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "hotel-inventory"
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql_data:
